import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation";



export const metadata: Metadata = {
  title: "Glamorize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-W900">
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
